//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr0gramm.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pr0gramm.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add tags.
        /// </summary>
        public static string AddTag {
            get {
                return ResourceManager.GetString("AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}ago.
        /// </summary>
        public static string Ago {
            get {
                return ResourceManager.GetString("Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No thanks.
        /// </summary>
        public static string AnswNo1 {
            get {
                return ResourceManager.GetString("AnswNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pr0gramm Viewer.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR0GRAMM VIEWER.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benis.
        /// </summary>
        public static string Benis {
            get {
                return ResourceManager.GetString("Benis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big view.
        /// </summary>
        public static string BigView {
            get {
                return ResourceManager.GetString("BigView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse tag.
        /// </summary>
        public static string BrowseTag {
            get {
                return ResourceManager.GetString("BrowseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by 
        /// </summary>
        public static string ByDeveloper {
            get {
                return ResourceManager.GetString("ByDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not be downloaded.
        /// </summary>
        public static string CannotSave {
            get {
                return ResourceManager.GetString("CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change every.
        /// </summary>
        public static string ChangeEvery {
            get {
                return ResourceManager.GetString("ChangeEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string ChangeSeconds {
            get {
                return ResourceManager.GetString("ChangeSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact me!.
        /// </summary>
        public static string ContactDeveloper {
            get {
                return ResourceManager.GetString("ContactDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy link.
        /// </summary>
        public static string CopyLink {
            get {
                return ResourceManager.GetString("CopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webm couldn&apos;t be loaded.
        /// </summary>
        public static string CouldNotLoadWebm {
            get {
                return ResourceManager.GetString("CouldNotLoadWebm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string DonateDeveloper {
            get {
                return ResourceManager.GetString("DonateDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noble donator.
        /// </summary>
        public static string Donator {
            get {
                return ResourceManager.GetString("Donator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficient.
        /// </summary>
        public static string Efficient {
            get {
                return ResourceManager.GetString("Efficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on download.
        /// </summary>
        public static string ErrorOnDownload {
            get {
                return ResourceManager.GetString("ErrorOnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on loading posts.
        /// </summary>
        public static string ErrorOnLoadingPosts {
            get {
                return ResourceManager.GetString("ErrorOnLoadingPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to log in.
        /// </summary>
        public static string ErrorOnLogIn {
            get {
                return ResourceManager.GetString("ErrorOnLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Could not send.
        /// </summary>
        public static string ErrorOnSending {
            get {
                return ResourceManager.GetString("ErrorOnSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pr0gramm Viewer is a 3rd party application, which uses the Pr0gramm.com API. The app only provides the content of the mentioned website and let user interact with the content..
        /// </summary>
        public static string Explanation {
            get {
                return ResourceManager.GetString("Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fag.
        /// </summary>
        public static string Fag {
            get {
                return ResourceManager.GetString("Fag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry to hear you didn&apos;t like my app.
        ///
        ///Please can you tell me how to improve my app?.
        /// </summary>
        public static string FeedbackMsg1 {
            get {
                return ResourceManager.GetString("FeedbackMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can I improve my app?.
        /// </summary>
        public static string FeedbackMsg2 {
            get {
                return ResourceManager.GetString("FeedbackMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to
        /// </summary>
        public static string FeedbackTo {
            get {
                return ResourceManager.GetString("FeedbackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  from .
        /// </summary>
        public static string FromLow {
            get {
                return ResourceManager.GetString("FromLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pr0gramm - Link to a Gif.
        /// </summary>
        public static string GifLink {
            get {
                return ResourceManager.GetString("GifLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give feedback.
        /// </summary>
        public static string GiveFeedback {
            get {
                return ResourceManager.GetString("GiveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hot.
        /// </summary>
        public static string Hot {
            get {
                return ResourceManager.GetString("Hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pr0gramm - Link to a hot post.
        /// </summary>
        public static string HotPostLink {
            get {
                return ResourceManager.GetString("HotPostLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to like.
        /// </summary>
        public static string LikeLower {
            get {
                return ResourceManager.GetString("LikeLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you experience any problems or have a few ideas on how to improve this app, then please send me an email:
        /// </summary>
        public static string LikeTextAbout {
            get {
                return ResourceManager.GetString("LikeTextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied link.
        /// </summary>
        public static string LinkCopied {
            get {
                return ResourceManager.GetString("LinkCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living legend.
        /// </summary>
        public static string LivingLegend {
            get {
                return ResourceManager.GetString("LivingLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load gifs.
        /// </summary>
        public static string LoadGifs {
            get {
                return ResourceManager.GetString("LoadGifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading posts....
        /// </summary>
        public static string LoadingPostsTrace {
            get {
                return ResourceManager.GetString("LoadingPostsTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load pictures.
        /// </summary>
        public static string LoadPicture {
            get {
                return ResourceManager.GetString("LoadPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load webms.
        /// </summary>
        public static string LoadWebms {
            get {
                return ResourceManager.GetString("LoadWebms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logindata.
        /// </summary>
        public static string LoginData {
            get {
                return ResourceManager.GetString("LoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comments.
        /// </summary>
        public static string ManualCommentsSwitch {
            get {
                return ResourceManager.GetString("ManualCommentsSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t load comments anymore. Comments can be still loaded via the button which appears right below the post. This feature enables faster loading times..
        /// </summary>
        public static string ManualCommentsSwitchText {
            get {
                return ResourceManager.GetString("ManualCommentsSwitchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod.
        /// </summary>
        public static string Mod {
            get {
                return ResourceManager.GetString("Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newfag.
        /// </summary>
        public static string Newfag {
            get {
                return ResourceManager.GetString("Newfag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} new messages.
        /// </summary>
        public static string NewMessagesCount {
            get {
                return ResourceManager.GetString("NewMessagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pr0gramm - Link.
        /// </summary>
        public static string NewPostLink {
            get {
                return ResourceManager.GetString("NewPostLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection to the internet possible.
        /// </summary>
        public static string NoNetworkConnection {
            get {
                return ResourceManager.GetString("NoNetworkConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any other posts.
        /// </summary>
        public static string NoOtherPostsFound {
            get {
                return ResourceManager.GetString("NoOtherPostsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldfag.
        /// </summary>
        public static string Oldfag {
            get {
                return ResourceManager.GetString("Oldfag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pr0gramm - Link to a picture.
        /// </summary>
        public static string PictureLink {
            get {
                return ResourceManager.GetString("PictureLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures without border.
        /// </summary>
        public static string PicturesWithoutBorder {
            get {
                return ResourceManager.GetString("PicturesWithoutBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points filter.
        /// </summary>
        public static string Pointsfilter {
            get {
                return ResourceManager.GetString("Pointsfilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR0SECRETSANTA.
        /// </summary>
        public static string ProWichtler {
            get {
                return ResourceManager.GetString("ProWichtler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like this app?.
        /// </summary>
        public static string QuestionNo1 {
            get {
                return ResourceManager.GetString("QuestionNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would appreciate it, if you&apos;d rate my app!
        ///
        ///If you like my app, it would motivate me to spend more time working on it!.
        /// </summary>
        public static string RatingMsg1 {
            get {
                return ResourceManager.GetString("RatingMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems like you are using my app rather often!
        ///
        ///Why don&apos;t you take some time to rate my app?.
        /// </summary>
        public static string RatingMsg2 {
            get {
                return ResourceManager.GetString("RatingMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string RatingNo {
            get {
                return ResourceManager.GetString("RatingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string RatingYes {
            get {
                return ResourceManager.GetString("RatingYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answer....
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the app to take effect on language.
        /// </summary>
        public static string RestartAppToTakeEffect {
            get {
                return ResourceManager.GetString("RestartAppToTakeEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searchfield.
        /// </summary>
        public static string SearchEntry {
            get {
                return ResourceManager.GetString("SearchEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsCaps {
            get {
                return ResourceManager.GetString("SettingsCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share picture.
        /// </summary>
        public static string SharePicture {
            get {
                return ResourceManager.GetString("SharePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Pr0gramm link.
        /// </summary>
        public static string SharePr0grammLink {
            get {
                return ResourceManager.GetString("SharePr0grammLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigationbuttons.
        /// </summary>
        public static string ShowNavigationButtons {
            get {
                return ResourceManager.GetString("ShowNavigationButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These buttons are shown on the side of pictures, webms and gifs. With those it is not necessary to swipe anymore..
        /// </summary>
        public static string ShowNavigationButtonsText {
            get {
                return ResourceManager.GetString("ShowNavigationButtonsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points onwards.
        /// </summary>
        public static string ShowPoints {
            get {
                return ResourceManager.GetString("ShowPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show slideshow.
        /// </summary>
        public static string ShowSlideshow {
            get {
                return ResourceManager.GetString("ShowSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statefilter.
        /// </summary>
        public static string StateFilter {
            get {
                return ResourceManager.GetString("StateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully loaded file.
        /// </summary>
        public static string SuccessOnDownload {
            get {
                return ResourceManager.GetString("SuccessOnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to donate me, you can do that under via PayPal.
        /// </summary>
        public static string SupportMe {
            get {
                return ResourceManager.GetString("SupportMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiletable owener.
        /// </summary>
        public static string TileTableOwner {
            get {
                return ResourceManager.GetString("TileTableOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type filter.
        /// </summary>
        public static string TypeFilter {
            get {
                return ResourceManager.GetString("TypeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlike.
        /// </summary>
        public static string Unlike {
            get {
                return ResourceManager.GetString("Unlike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlike.
        /// </summary>
        public static string UnlikeLower {
            get {
                return ResourceManager.GetString("UnlikeLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploads.
        /// </summary>
        public static string Uploads {
            get {
                return ResourceManager.GetString("Uploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit profile.
        /// </summary>
        public static string VisitProfile {
            get {
                return ResourceManager.GetString("VisitProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string VoteTag {
            get {
                return ResourceManager.GetString("VoteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pr0gramm - Link to a webm.
        /// </summary>
        public static string WebmLink {
            get {
                return ResourceManager.GetString("WebmLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what&apos;s new?.
        /// </summary>
        public static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
    }
}
